import type { Car, CarImage, CarWithImages, InspectionReport, SellRequest, Lead, Appointment, BlogPost, Testimonial, Transaction } from '@/types/database'

// ── MOCK DATA ──────────────────────────────────────────────────────────────────
// Used while Supabase is not connected (placeholder mode)

export const MOCK_CARS: CarWithImages[] = [
  {
    id: '1',
    title: 'Toyota Premio 2018',
    title_bn: 'টয়োটা প্রিমিও ২০১৮',
    brand: 'Toyota',
    model: 'Premio',
    variant: 'X L Package',
    year: 2018,
    price: 3200000,
    negotiable: true,
    status: 'available',
    body_type: 'sedan',
    fuel_type: 'petrol',
    transmission: 'automatic',
    mileage: 48000,
    color: 'White Pearl',
    engine_cc: 1800,
    engine_type: '2ZR-FE',
    horsepower: 132,
    seats: 5,
    doors: 4,
    registration_year: 2019,
    tax_token_valid: true,
    fitness_valid: true,
    insurance_valid: true,
    ownership_count: 1,
    accident_history: false,
    certified: true,
    just_arrived: true,
    featured: true,
    thumbnail_url: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800',
    description: 'Excellent condition Toyota Premio with full service history. Single owner, non-accident vehicle.',
    description_bn: 'চমৎকার অবস্থায় টয়োটা প্রিমিও, সম্পূর্ণ সার্ভিস হিস্ট্রি সহ।',
    features: ['Push Start', 'Leather Seats', 'Sunroof', 'Reverse Camera', 'Keyless Entry', 'LED Headlights'],
    purchase_price: 2900000,
    created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    car_images: [
      { id: '1a', car_id: '1', url: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=1200', alt: 'Front', order_index: 0, is_primary: true },
      { id: '1b', car_id: '1', url: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=1200', alt: 'Side', order_index: 1, is_primary: false },
      { id: '1c', car_id: '1', url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200', alt: 'Interior', order_index: 2, is_primary: false },
    ],
  },
  {
    id: '2',
    title: 'Toyota Axio 2017',
    title_bn: 'টয়োটা অ্যাক্সিও ২০১৭',
    brand: 'Toyota',
    model: 'Axio',
    variant: 'G',
    year: 2017,
    price: 2400000,
    negotiable: false,
    status: 'available',
    body_type: 'sedan',
    fuel_type: 'hybrid',
    transmission: 'cvt',
    mileage: 62000,
    color: 'Silver',
    engine_cc: 1500,
    seats: 5,
    registration_year: 2018,
    tax_token_valid: true,
    fitness_valid: true,
    insurance_valid: true,
    ownership_count: 2,
    accident_history: false,
    certified: true,
    just_arrived: false,
    featured: true,
    thumbnail_url: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
    description: 'Well maintained Toyota Axio Hybrid. Excellent fuel efficiency.',
    created_at: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    car_images: [
      { id: '2a', car_id: '2', url: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200', alt: 'Front', order_index: 0, is_primary: true },
    ],
  },
  {
    id: '3',
    title: 'Honda Vezel 2019',
    title_bn: 'হোন্ডা ভেজেল ২০১৯',
    brand: 'Honda',
    model: 'Vezel',
    variant: 'Hybrid Z',
    year: 2019,
    price: 4100000,
    negotiable: true,
    status: 'available',
    body_type: 'suv',
    fuel_type: 'hybrid',
    transmission: 'cvt',
    mileage: 35000,
    color: 'Red',
    engine_cc: 1500,
    seats: 5,
    registration_year: 2020,
    tax_token_valid: true,
    fitness_valid: true,
    insurance_valid: true,
    ownership_count: 1,
    accident_history: false,
    certified: true,
    just_arrived: true,
    featured: true,
    thumbnail_url: 'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800',
    description: 'Stunning Honda Vezel Hybrid in excellent condition. Low mileage, single owner.',
    features: ['Honda Sensing', 'Apple CarPlay', 'LED Headlights', 'Panoramic Sunroof', 'Heated Seats'],
    purchase_price: 3700000,
    created_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    car_images: [
      { id: '3a', car_id: '3', url: 'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=1200', alt: 'Front', order_index: 0, is_primary: true },
    ],
  },
  {
    id: '4',
    title: 'Toyota Land Cruiser Prado 2016',
    title_bn: 'টয়োটা ল্যান্ড ক্রুজার প্রাডো ২০১৬',
    brand: 'Toyota',
    model: 'Land Cruiser Prado',
    variant: 'TX-L',
    year: 2016,
    price: 9800000,
    negotiable: true,
    status: 'available',
    body_type: 'suv',
    fuel_type: 'diesel',
    transmission: 'automatic',
    mileage: 95000,
    color: 'Black',
    engine_cc: 2800,
    engine_type: '1GD-FTV',
    horsepower: 204,
    seats: 7,
    registration_year: 2017,
    tax_token_valid: true,
    fitness_valid: true,
    insurance_valid: true,
    ownership_count: 2,
    accident_history: false,
    certified: true,
    just_arrived: false,
    featured: true,
    thumbnail_url: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=800',
    description: 'Premium Toyota Land Cruiser Prado in excellent condition. Full options package.',
    features: ['4WD', 'Kdss Suspension', 'Leather Seats', 'JBL Sound', 'Downhill Assist', 'Multi Terrain Monitor'],
    purchase_price: 8900000,
    created_at: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    car_images: [
      { id: '4a', car_id: '4', url: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=1200', alt: 'Front', order_index: 0, is_primary: true },
    ],
  },
  {
    id: '5',
    title: 'Nissan X-Trail 2018',
    title_bn: 'নিসান এক্স-ট্রেইল ২০১৮',
    brand: 'Nissan',
    model: 'X-Trail',
    variant: '20Xi',
    year: 2018,
    price: 3800000,
    negotiable: false,
    status: 'available',
    body_type: 'suv',
    fuel_type: 'petrol',
    transmission: 'cvt',
    mileage: 55000,
    color: 'White',
    engine_cc: 2000,
    seats: 7,
    registration_year: 2019,
    tax_token_valid: true,
    fitness_valid: true,
    insurance_valid: true,
    ownership_count: 1,
    accident_history: false,
    certified: true,
    just_arrived: false,
    featured: false,
    thumbnail_url: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800',
    description: 'Spacious Nissan X-Trail with 7-seat configuration. Perfect for families.',
    purchase_price: 3400000,
    created_at: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    car_images: [
      { id: '5a', car_id: '5', url: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=1200', alt: 'Front', order_index: 0, is_primary: true },
    ],
  },
  {
    id: '6',
    title: 'BMW 3 Series 2017',
    title_bn: 'বিএমডব্লিউ ৩ সিরিজ ২০১৭',
    brand: 'BMW',
    model: '3 Series',
    variant: '320i Sport Line',
    year: 2017,
    price: 6500000,
    negotiable: true,
    status: 'available',
    body_type: 'sedan',
    fuel_type: 'petrol',
    transmission: 'automatic',
    mileage: 72000,
    color: 'Mineral Grey',
    engine_cc: 2000,
    engine_type: 'B48B20A',
    horsepower: 184,
    seats: 5,
    registration_year: 2018,
    tax_token_valid: true,
    fitness_valid: true,
    insurance_valid: true,
    ownership_count: 2,
    accident_history: false,
    certified: false,
    just_arrived: false,
    featured: false,
    thumbnail_url: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
    description: 'Sporty BMW 3 Series with all sport package. Excellent driving dynamics.',
    purchase_price: 5800000,
    created_at: new Date(Date.now() - 14 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    car_images: [
      { id: '6a', car_id: '6', url: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=1200', alt: 'Front', order_index: 0, is_primary: true },
    ],
  },
  {
    id: '7',
    title: 'Toyota Noah 2017',
    title_bn: 'টয়োটা নোয়া ২০১৭',
    brand: 'Toyota',
    model: 'Noah',
    variant: 'Hybrid G',
    year: 2017,
    price: 4500000,
    negotiable: true,
    status: 'available',
    body_type: 'microbus',
    fuel_type: 'hybrid',
    transmission: 'cvt',
    mileage: 43000,
    color: 'Silver',
    engine_cc: 1800,
    seats: 8,
    registration_year: 2018,
    tax_token_valid: true,
    fitness_valid: true,
    insurance_valid: true,
    ownership_count: 1,
    accident_history: false,
    certified: true,
    just_arrived: true,
    featured: false,
    thumbnail_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    description: 'Perfect family microbus with 8 seats and hybrid engine.',
    purchase_price: 4100000,
    created_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    car_images: [
      { id: '7a', car_id: '7', url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200', alt: 'Front', order_index: 0, is_primary: true },
    ],
  },
  {
    id: '8',
    title: 'Mitsubishi Outlander 2019',
    title_bn: 'মিতসুবিশি আউটল্যান্ডার ২০১৯',
    brand: 'Mitsubishi',
    model: 'Outlander',
    variant: 'PHEV',
    year: 2019,
    price: 5200000,
    negotiable: true,
    status: 'reserved',
    body_type: 'suv',
    fuel_type: 'hybrid',
    transmission: 'automatic',
    mileage: 28000,
    color: 'Deep Blue',
    engine_cc: 2400,
    seats: 7,
    registration_year: 2020,
    tax_token_valid: true,
    fitness_valid: true,
    insurance_valid: true,
    ownership_count: 1,
    accident_history: false,
    certified: true,
    just_arrived: false,
    featured: false,
    thumbnail_url: 'https://images.unsplash.com/photo-1532974297617-c0f05fe48bff?w=800',
    description: 'Plug-in Hybrid SUV with all-wheel drive. Superb fuel economy.',
    purchase_price: 4700000,
    created_at: new Date(Date.now() - 20 * 24 * 3600 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    car_images: [
      { id: '8a', car_id: '8', url: 'https://images.unsplash.com/photo-1532974297617-c0f05fe48bff?w=1200', alt: 'Front', order_index: 0, is_primary: true },
    ],
  },
]

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Md. Rakibul Islam',
    rating: 5,
    review: 'Excellent service! I sold my Toyota Premio in just 2 days. SR Car Gallery gave me a fair price and handled all the paperwork. Highly recommended!',
    review_bn: 'চমৎকার সেবা! মাত্র ২ দিনে আমার টয়োটা প্রিমিও বিক্রি হয়ে গেল। ন্যায্য দাম পেয়েছি।',
    car_bought: 'Sold Toyota Premio 2017',
    date: '2024-12-15',
    verified: true,
    created_at: '2024-12-15',
  },
  {
    id: '2',
    name: 'Farhan Ahmed',
    rating: 5,
    review: 'Bought a Honda Vezel from SR Car Gallery. The inspection report gave me full confidence. The team was transparent and professional throughout.',
    review_bn: 'হোন্ডা ভেজেল কিনেছি। ইন্সপেকশন রিপোর্ট আমাকে সম্পূর্ণ আস্থা দিয়েছে।',
    car_bought: 'Honda Vezel Hybrid 2019',
    date: '2024-11-28',
    verified: true,
    created_at: '2024-11-28',
  },
  {
    id: '3',
    name: 'Nusrat Jahan',
    rating: 5,
    review: 'As a first-time buyer, I was nervous, but the team at SR Car Gallery made everything so easy. My Toyota Axio is running perfectly!',
    review_bn: 'প্রথমবার গাড়ি কিনতে ভয় পেয়েছিলাম, কিন্তু SR Car Gallery এর দল সব কিছু সহজ করে দিয়েছে।',
    car_bought: 'Toyota Axio Hybrid 2018',
    date: '2025-01-10',
    verified: true,
    created_at: '2025-01-10',
  },
  {
    id: '4',
    name: 'Imran Hossain',
    rating: 4,
    review: 'Great experience selling my car. Quick valuation, same-day offer, and fast payment. Will definitely come back for my next purchase.',
    review_bn: 'গাড়ি বিক্রির অভিজ্ঞতা চমৎকার। দ্রুত মূল্যায়ন, একই দিনে অফার এবং দ্রুত পেমেন্ট।',
    car_bought: 'Sold BMW 3 Series 2016',
    date: '2025-02-05',
    verified: true,
    created_at: '2025-02-05',
  },
]

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'How to Check a Used Car Before Buying in Bangladesh',
    title_bn: 'বাংলাদেশে পুরানো গাড়ি কেনার আগে কীভাবে চেক করবেন',
    slug: 'how-to-check-used-car-before-buying-bangladesh',
    excerpt: 'A complete guide to inspecting a second-hand car before purchase. Learn what to look for and how to avoid common pitfalls.',
    cover_image: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800',
    author: 'SR Car Gallery',
    category: 'Buying Guide',
    tags: ['buying guide', 'inspection', 'used cars'],
    published: true,
    content: 'Full content here...',
    created_at: '2025-01-15',
    updated_at: '2025-01-15',
  },
  {
    id: '2',
    title: 'Top 5 Used Cars to Buy in Dhaka Under 30 Lac',
    title_bn: 'ঢাকায় ৩০ লক্ষের নিচে কেনার সেরা ৫টি গাড়ি',
    slug: 'top-5-used-cars-dhaka-under-30-lac',
    excerpt: 'Best value-for-money used cars available in Dhaka\'s market right now. Toyota, Honda, and more options under BDT 30 Lac.',
    cover_image: 'https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800',
    author: 'SR Car Gallery',
    category: 'Market Guide',
    tags: ['market', 'budget cars', 'best value'],
    published: true,
    content: 'Full content here...',
    created_at: '2025-02-01',
    updated_at: '2025-02-01',
  },
  {
    id: '3',
    title: 'How to Get the Best Price When Selling Your Car in Bangladesh',
    title_bn: 'বাংলাদেশে গাড়ি বিক্রিতে সর্বোচ্চ দাম পাওয়ার উপায়',
    slug: 'best-price-selling-car-bangladesh',
    excerpt: 'Expert tips to maximize your car\'s resale value. From preparation to negotiation — a complete seller\'s guide.',
    cover_image: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800',
    author: 'SR Car Gallery',
    category: 'Selling Guide',
    tags: ['selling', 'tips', 'valuation'],
    published: true,
    content: 'Full content here...',
    created_at: '2025-02-20',
    updated_at: '2025-02-20',
  },
]
